@startuml

class User {
    '사용자 공통 필드
    - UUID id /' Firestore 문서 id를 그대로 사용 '/
    - UserType user_type
    - TimeStamp created_at
    - String email
    - String password
    - String user_name
    - String phone_number
    '관리자 전용 필드
    - String? business_number
    - String? store_name
    - String? store_location
}

class Store {
    - UUID id /' Firestore 문서 id를 그대로 사용 '/
    - UUID owner_id /' Firestore 문서 id를 그대로 사용 '/
    - String store_name
    - String owner_name
    - StoreCategory category
    - String business_number
    - TimeStamp opened_at
    - TimeStamp closed_at
    - String address
}

@enduml